---
- name: Configuring Flatpak and Flabhub.
  hosts: fedora_ws_vm
  become: yes
  vars:
    flatpak_repo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"

  tasks:
    - name: Installing flatpak.
      ansible.builtin.dnf:
        name: flatpak
        state: present

    - name: Enabling Flathub.
      community.general.flatpak_remote:
        name: flathub # should be lowercased.
        state: present
        flatpakrepo_url: "{{ flatpak_repo_url }}"
        method: "system"



