---
- name: Setting up Zen Browser
  hosts: fedora_ws_vm
  become: no

  tasks:
    - name: Download the browser from official website.
      ansible.builtin.get_url:
        url: 'https://github.com/zen-browser/desktop/releases/latest/download/zen.linux-x86_64.tar.xz'
        dest: '~/Downloads/zen.linux-x86_64.tar.xz'

